project_name: secretr

builds:
  - main: ./cmd/main.go
    binary: secretr
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    ldflags: "-s -w"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

# Packaging for Linux distributions
dockers: []
nfpms:
  - id: default
    packager: deb
    formats:
      - deb
    files:
      - src: secretr
        dst: /usr/local/bin/secretr
    info:
      name: secretr
      arch: amd64
      maintainer: "Your Name <you@example.com>"
      description: "Secret application"
  - id: rpm
    packager: rpm
    formats:
      - rpm
    files:
      - src: secretr
        dst: /usr/local/bin/secretr
    info:
      name: secretr
      arch: amd64
      maintainer: "Your Name <you@example.com>"
      description: "Secret application"

release:
  github:
    owner: your-github-username
    name: secretr
