name: SLSA Go Releaser

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  build:
    # pick runner per entry in the matrix
    runs-on: ${{ matrix.runs-on }}

    permissions:
      id-token: write
      contents: write
      actions: read

    strategy:
      matrix:
        include:
          # Linux builds (Ubuntu)
          - goos: linux
            goarch: amd64
            runs-on: ubuntu-latest
          - goos: linux
            goarch: arm64
            runs-on: ubuntu-latest

          # macOS builds (macOS)
          - goos: darwin
            goarch: amd64
            runs-on: macos-latest
          - goos: darwin
            goarch: arm64
            runs-on: macos-latest

          # Windows build (Windows x64 only)
          - goos: windows
            goarch: amd64
            runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # Install GLFW deps only on Ubuntu
      - name: Install system dependencies for GLFW (Ubuntu)
        if: matrix.runs-on == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgl1-mesa-dev \
            xorg-dev \
            libxcursor-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxi-dev \
            libxxf86vm-dev \
            libx11-dev

      - name: Verify go.sum exists
        run: |
          test -f go.sum || (echo "❌ go.sum is missing!" && exit 1)
          echo "✅ go.sum found"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-mod-${{ runner.os }}-v3-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-mod-${{ runner.os }}-v3-

      - name: Build vault for ${{ matrix.goos }}/${{ matrix.goarch }}
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 1
        run: |
          ext=""
          if [ "${{ matrix.goos }}" = "windows" ]; then
            ext=".exe"
          fi
          go build -v -o vault-${{ matrix.goos }}-${{ matrix.goarch }}${ext} ./cmd

      - name: Publish binaries to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            vault-*-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
