name: SLSA Go Releaser

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  build:
    permissions:
      id-token: write     # Required to sign artifacts
      contents: write     # Required to upload to releases
      actions: read       # Required to read reusable workflows
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.5.0
    with:
      go-version: 1.24.2
