name: SLSA Go Releaser

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      actions: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install system dependencies for GLFW
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgl1-mesa-dev \
            xorg-dev \
            libxcursor-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxi-dev \
            libxxf86vm-dev \
            libx11-dev

      - name: Verify go.sum exists
        run: |
          if [ ! -f go.sum ]; then
            echo "❌ go.sum is missing!"
            exit 1
          fi
          echo "✅ go.sum found"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-mod-${{ runner.os }}-v3-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-mod-${{ runner.os }}-v3-

      - name: Build binary
        run: go build -v -o vault ./cmd
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vault
          path: ./vault
